version: '3'
services:
  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    image: acm-api-gateway:1.0
    ports:
      - "80:80"
    restart: always
    container_name: api-gateway
    depends_on:
      - discovery
      - config-server

  discovery:
    build:
      context: discovery
      dockerfile: Dockerfile
    image: acm-discovery:1.0
    ports:
      - "8761:8761"
    restart: always
    container_name: discovery

  config-server:
    build:
      context: config-server
      dockerfile: Dockerfile
    image: acm-config-server:1.0
    ports:
      - "8001:8001"
    restart: always
    container_name: config-server

  postgres-acm:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ACM
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - $HOME/postgres/data:/var/lib/postgresql/data
    container_name: postgres-acm

  mongodb-acm:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - $HOME/mongodb/data:/data/db
    container_name: mongodb-acm

  device-monitoring-service:
    build:
      context: device-monitoring-service
      dockerfile: Dockerfile
    image: acm-device-monitoring:1.0
    ports:
      - "8084:8084"
    restart: always
    container_name: device-monitoring-service

  stats-service:
    build:
      context: stats-service
      dockerfile: Dockerfile
    image: acm-stats-service:1.0
    ports:
      - "8085:8085"
    restart: always
    container_name: stats-service

networks:
  default:
